language: java

jdk:
- oraclejdk7

cache:
  directories:
  - "$HOME/.m2/repository"

script:
  - mvn clean test
  

env:
	global:
	- CODECOV_TOKEN=:e151ca70-8015-43f1-8886-b7291b6b7388
after_success:
  - bash <(curl -s https://codecov.io/bash) -t token