language: java

jdk:
- oraclejdk7

cache:
  directories:
  - "$HOME/.m2/repository"

script:
  - mvn clean test
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -t e151ca70-8015-43f1-8886-b7291b6b7388